Support compiling mainline kernel from local git repository
* `pmbootstrap init` allows to specify a local linux kernel repository
* New `--local-src` parameter for `pmbootstrap build`:
  `pmbootstrap build linux-postmarketos-mainline --arch=armhf --local-src`
  - Mounts the kernel source to /mnt/pmbootstrap-local-src inside the
    chroot
  - exports `PMB_LOCAL_SRC=/mnt/pmbootstrap-local-src` to `abuild`
* `pmb/helpers/frontend.py`: Verifies, that the packages passed to
  `pmbootstrap build` use `PMB_LOCAL_SRC` when `--local-src` is
  specificed and raise an exception if they don't
* linux-postmarketos-mainline APKBUILD adjustments:
  - update linux-v4.14-v4.15-rc6.patch checksum to upstream (they
    probably updated their git/patch tool, which caused a different
    checksum)
  - fetch(): don't download anything when using `--local-src`
  - unpack(): don't extract anything, but create a link to
    `$PMB_LOCAL_SRC` if it is specified
  - prepare(): don't apply any patches to the kernel source folder
    when using `--local-src`
  - package(): change the `pkgdesc` when using `--local-src`

diff --git a/aports/main/linux-postmarketos-mainline/APKBUILD b/aports/main/linux-postmarketos-mainline/APKBUILD
--- a/aports/main/linux-postmarketos-mainline/APKBUILD
+++ b/aports/main/linux-postmarketos-mainline/APKBUILD
@@ -9,7 +9,7 @@ _kernver=${pkgver%_rc*}
 _mainver=${_kernver%.*}
 _patchlevel=${_kernver/$_mainver./}
 _basever=${_mainver}.$((_patchlevel-1))
-pkgrel=3
+pkgrel=4
 
 arch="x86_64 armhf aarch64"
 pkgdesc="Linux for pmOS supported chipsets (mainline, more bleeding-edge than stable)"
@@ -45,27 +45,47 @@ HOSTCC="${HOSTCC#${CROSS_COMPILE}}"
 
 ksrcdir="$srcdir/linux-$_basever"
 
-prepare() {
-	local _patch_failed=
-	cd "$ksrcdir"
-	# first apply patches in specified order
-	for i in $source; do
-		case $i in
-		*.patch|*.patch::*)
-			_patch=${i%::*}
-			msg "Applying $_patch..."
-			if ! patch -s -p1 -N -i "$srcdir"/$_patch; then
-				echo $_patch >>failed
-				_patch_failed=1
-			fi
-			;;
-		esac
-	done
+fetch() {
+	if [ -z "$PMB_LOCAL_SRC" ]; then
+		default_fetch
+	else
+		mkdir -p "$srcdir"
+		ln -svf "$startdir/$_config" "$srcdir/$_config"
+	fi
+}
 
-	if ! [ -z "$_patch_failed" ]; then
-		error "The following patches failed:"
-		cat failed
-		return 1
+unpack() {
+	if [ -z "$PMB_LOCAL_SRC" ]; then
+		default_unpack
+	else
+		msg "Using local kernel sources: $PMB_LOCAL_SRC"
+		ln -sv "$PMB_LOCAL_SRC" "$ksrcdir"
+	fi
+}
+
+prepare() {
+	if [ -z "$PMB_LOCAL_SRC" ]; then
+		local _patch_failed=
+		cd "$ksrcdir"
+		# first apply patches in specified order
+		for i in $source; do
+			case $i in
+			*.patch|*.patch::*)
+				_patch=${i%::*}
+				msg "Applying $_patch..."
+				if ! patch -s -p1 -N -i "$srcdir"/$_patch; then
+					echo $_patch >>failed
+					_patch_failed=1
+				fi
+				;;
+			esac
+		done
+
+		if ! [ -z "$_patch_failed" ]; then
+			error "The following patches failed:"
+			cat failed
+			return 1
+		fi
 	fi
 
 	mkdir -p "$srcdir"/build
@@ -92,6 +112,11 @@ build() {
 }
 
 package() {
+	if ! [ -z "$PMB_LOCAL_SRC" ]; then
+		pkgdesc="LOCAL KERNEL SOURCE USED"
+		msg "Set pkgdesc to: $pkgdesc"
+	fi
+
 	cd "$srcdir/build/arch/${_carch}/boot"
 
 	if [ "$CARCH" == "aarch64" ]; then
